server:
  port: 8080
name: hellokitty
student:
  name: testkitty
  age: 30
spring:
  data:
    mongodb:
      uri: mongodb://testuser:123456@47.100.241.71:27017/testdb?authSource=admin
  redis:
    host: 47.100.241.71
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
  rabbitmq:
    host: 47.100.241.71
    port: 5672
    username: hello
    password: kitty
jwt:
  header: Authorization
  secret: ibWKhrDSro02CaBtGIopnofGVFYCRTXQPArcnJIpxMRBP5sGk7ufiyVZtUXsQXvk
  expiration: 604800
  tokenHead: hellokitty